# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build

on:
  push:
    branches:
      - "**/*"
  schedule:
    # Minute (0-59), Hour (0-23), Day of the month (1-31), Month of the Year (1-12), Day of the week (0-6, 0 = Sunday)
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build the Docker image
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Build the image
        run: |
          docker build -t alphahydrae/scronpt:build .
